id: P003225
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:38.678722
source_metadata:
  id: bdr:W1KG21089
  title: བརྡ་དག་མིང་ཚིག་གསལ་བ།
  author: ''
  volumes:
    d294a18502ed44b1ab479f67c0eb6846:
      image_group_id: I1KG21120
      title: ''
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
    c545985641664cbfa25ada21ae00b21b:
      image_group_id: I1KG21121
      title: ''
      volume_number: 2
      total_pages: 646
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
