id: I2F6CC2F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:40:48+00:00'
last_modified: '2022-06-07T18:30:07.888007+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21089
  title: བརྡ་དག་མིང་ཚིག་གསལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '0057':
      image_group_id: I1KG21120
      title: ''
      total_pages: 536
      order: 1
      base_file: 0057.txt
    '6427':
      image_group_id: I1KG21121
      title: ''
      total_pages: 646
      order: 2
      base_file: 6427.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
